import Head from 'next/head'


import MuiTypography from '../components/MuiTypography'
import MuiButton from '../components/MuiButton'
import MuiTextField from '../components/MuiTextField'
import MuiSelect from '../components/MuiSelect'
import MuiRadioButton from '../components/MuiRadioButton'
import MuiCheckbox from '../components/MuiCheckbox'
import MuiSwitch from '../components/MuiSwitch'
import MuiRating from '../components/MuiRating'
import MuiAutoComplete from '../components/MuiAutoComplete'
import MuiLayout from '../components/MuiLayout'
import MuiCard from '../components/MuiCard'
import MuiAccordion from '../components/MuiAccordion'
import MuiImageList from '../components/MuiImageList'
import MuiNavbar from '../components/MuiNavbar'
import MuiLink from '../components/MuiLink'
import MuiBreadCrumbs from '../components/MuiBreadCrumbs'
import MuiDrawer from '../components/MuiDrawer'
import MuiSpeedDial from '../components/MuiSpeedDial'
import MuiBottomNavigation from '../components/MuiBottomNavigation'
import MuiAvatar from '../components/MuiAvatar'
import MuiBadge from '../components/MuiBadge'
import MuiList from '../components/MuiList'
import MuiChip from '../components/MuiChip'
import MuiTooltip from '../components/MuiTooltip'
import MuiTable from '../components/MuiTable'
import MuiAlert from '../components/MuiAlert'
import MuiSnackbar from '../components/MuiSnackbar'
import MuiDialog from '../components/MuiDialog'
import MuiProgress from '../components/MuiProgress'
import MuiSkeleton from '../components/MuiSkeleton'
import MuiLoadingButton from '../components/MuiLoadingButton'
import MuiDateTimePicker from '../components/MuiDateTimePicker'


import { LocalizationProvider } from '@mui/lab'
import AdapterDateFns from "@mui/lab/AdapterDateFns"
import MuiDateRangePicker from '../components/MuiDateRangePicker'

import MuiTabs from '../components/MuiTabs'
import MuiTimeline from '../components/MuiTimeLine'
import MuiMasonry from '../components/MuiMasonry'
import MuiResponsiveness from '../components/MuiResponsiveness'



export default function Home() {
  return (
      <LocalizationProvider dateAdapter={AdapterDateFns}>

        <div>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          {/* <MuiTypography /> */}
          {/* <MuiButton /> */}
          {/* <MuiTextField /> */}
          {/* <MuiSelect /> */}
          {/* <MuiRadioButton /> */}
          {/* <MuiCheckbox /> */}
          {/* <MuiSwitch /> */}
          {/* <MuiRating /> */}
          {/* <MuiAutoComplete /> */}
          {/* <MuiLayout /> */}
          {/* <MuiCard /> */}
          {/* <MuiAccordion /> */}
          {/* <MuiImageList /> */}
          <MuiNavbar />
          {/* <MuiLink /> */}
          {/* <MuiBreadCrumbs /> */}
          {/* <MuiDrawer /> */}
          {/* <MuiSpeedDial /> */}
          {/* <MuiBottomNavigation /> */}
          {/* <MuiAvatar /> */}
          {/* <MuiBadge /> */}
          {/* <MuiList /> */}
          {/* <MuiChip /> */}
          {/* <MuiTooltip /> */}
          {/* <MuiTable /> */}
          {/* <MuiAlert /> */}
          {/* <MuiSnackbar /> */}
          {/* <MuiDialog /> */}
          {/* <MuiProgress /> */}
          {/* <MuiSkeleton /> */}
          {/* <MuiLoadingButton /> */}
          {/* <MuiDateTimePicker />  */}
          {/* <MuiDateRangePicker /> ????????????????? */}
          {/* <MuiTabs /> */}
          {/* <MuiTimeline /> */}
          {/* <MuiMasonry /> */}
          <MuiResponsiveness />
          
        </div>
      </LocalizationProvider>
  )
}
